// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const axios = require('axios')

describe('SearchDG', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SearchDG', async function() {
    try {
      // Add sorting parameters to the URL
      await driver.get("https://web.stage.vcc.hebronsoft.com/donations-needed?order=DESC&orderBy=updated")
      await driver.manage().window().setRect({ width: 1440, height: 900 })
      await driver.findElement(By.xpath("(//input[@type=\'text\'])[2]")).click()
      await driver.findElement(By.xpath("(//input[@type=\'text\'])[2]")).sendKeys("test")
      
      // Wait for search results to load
      await driver.sleep(2000)
      
      // Find all h4 elements with the specified class
      const titles = await driver.findElements(By.css('h4.font-semibold.text-24pxlh30px.h-\\[60px\\].font-Montserrat.truncate'))
      
      // Count items with exact "test" in their title
      let testCount = 0
      for (const title of titles) {
          const text = await title.getText()
          if (text.toLowerCase().includes('test')) {
              testCount++
          }
      }
      
      console.log(`Number of items with "test" in title: ${testCount}`)

      // Verify sorting by checking API response
      const response = await axios.post('https://api.stage.vcc.hebronsoft.com/web-api/need/list', 
          {
              filter: { search: "test" },
              query: {
                  limit: "30",
                  offset: "0",
                  order: "DESC",
                  orderBy: "updated"
              }
          },
          {
              headers: {
                  'Accept': 'application/json, text/plain, */*',
                  'Accept-Language': 'uk-UA,uk;q=0.9,en-US;q=0.8,en;q=0.7',
                  'Connection': 'keep-alive',
                  'Content-Type': 'application/json',
                  'Origin': 'https://web.stage.vcc.hebronsoft.com',
                  'Referer': 'https://web.stage.vcc.hebronsoft.com/',
                  'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36',
                  'sec-ch-ua': '"Google Chrome";v="135", "Not-A.Brand";v="8", "Chromium";v="135"',
                  'sec-ch-ua-mobile': '?0',
                  'sec-ch-ua-platform': '"macOS"'
              }
          }
      )
      
      const items = response.data.data
      
      // Log all items with their update dates for verification
      console.log('\nItems sorted by updated date (DESC):')
      items.forEach((item, index) => {
          console.log(`${index + 1}. Title: ${item.title}, Updated: ${item.updated}`)
      })
      
      // Verify items are sorted by updated date in descending order
      let previousDate = null
      for (const item of items) {
          const currentDate = new Date(item.updated)
          
          if (previousDate) {
              assert(
                  currentDate <= previousDate,
                  `Items are not sorted in descending order by update date:\nCurrent: ${item.title} (${item.updated})\nPrevious: ${previousDate.toISOString()}`
              )
          }
          
          previousDate = currentDate
      }

      console.log('\nSorting verification completed successfully - all items are correctly sorted by updated date in descending order')
    } catch (error) {
      console.error('Test failed:', error)
      throw error
    }
  })
})