// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const axios = require('axios')

describe('searchV', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('searchV', async function() {
    // Make API call to verify sorting
    const apiResponse = await axios.post('https://api.stage.vcc.hebronsoft.com/web-api/project/list', 
      {
        filter: {
          search: "help",
          courtOrderedService: false
        },
        query: {
          limit: "30",
          offset: "0",
          order: "DESC",
          orderBy: "updated"
        }
      },
      {
        headers: {
          'Accept': 'application/json, text/plain, */*',
          'Accept-Language': 'uk-UA,uk;q=0.9,en-US;q=0.8,en;q=0.7',
          'Content-Type': 'application/json',
          'Origin': 'https://web.stage.vcc.hebronsoft.com',
          'Referer': 'https://web.stage.vcc.hebronsoft.com/'
        }
      }
    )

    // Verify sorting in API response
    const items = apiResponse.data.data
    let isSorted = true
    let previousTimestamp = null

    // Log formatted list of items
    console.log('\nItems sorted by updated date (DESC):')
    items.forEach((item, index) => {
        console.log(`${index + 1}. Title: ${item.title}, Updated: ${item.updated}`)
    })

    for (const item of items) {
      const currentTimestamp = new Date(item.updated)
      if (previousTimestamp && currentTimestamp > previousTimestamp) {
        isSorted = false
        break
      }
      previousTimestamp = currentTimestamp
    }

    // Log API results
    console.log(`\nAPI Response: Found ${items.length} items`)
    console.log(`API Results are sorted by updated date in descending order: ${isSorted}`)
    
    // Verify sorting in UI
    await driver.get("https://web.stage.vcc.hebronsoft.com/volunteering-opportunities")
    await driver.manage().window().setRect({ width: 1440, height: 900 })
    await driver.findElement(By.xpath("//div/div/div/div[2]/div")).click()
    await driver.findElement(By.xpath("(//input[@type='text'])[2]")).click()
    await driver.findElement(By.xpath("(//input[@type='text'])[2]")).sendKeys("help")
    
    // Wait for search results to load
    await driver.sleep(2000)
    
    // Find all h4 elements with the specified class
    const titles = await driver.findElements(By.css('h4.font-semibold.text-24pxlh30px.h-\\[60px\\].font-Montserrat.truncate'))
    
    // Count items with "help" in their title
    let helpCount = 0
    for (const title of titles) {
        const text = await title.getText()
        if (text.toLowerCase().includes('help')) {
            helpCount++
        }
    }
    
    // Log UI results
    console.log(`\nUI Results: Found ${helpCount} items with "help" in title`)
    
    // Assert both API and UI conditions
    assert.ok(isSorted, 'API results should be sorted by updated date in descending order')
    assert.ok(helpCount > 0, 'Should find at least one item with "help" in title')
    assert.ok(items.length > 0, 'API should return at least one item')
  })
})


