// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const axios = require('axios')

describe('SearchCP', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SearchCP', async function() {
    try {
      // Make API call to get sorted data
      const response = await axios.post('https://api.stage.vcc.hebronsoft.com/web-api/community-partner/list', {
        filter: { search: "organization" },
        query: {
          limit: "50",
          offset: "0",
          order: "ASC",
          orderBy: "random",
          cursor: 3
        }
      }, {
        headers: {
          'Accept': 'application/json, text/plain, */*',
          'Content-Type': 'application/json',
          'Origin': 'https://web.stage.vcc.hebronsoft.com'
        }
      });

      // Verify sorting parameters in response
      assert.strictEqual(response.data.order, "ASC", "Order should be ASC");
      assert.strictEqual(response.data.orderBy, "random", "OrderBy should be random");

      // Navigate to the page
      await driver.get("https://web.stage.vcc.hebronsoft.com/community-partners")
      await driver.manage().window().setRect({ width: 1440, height: 900 })
      
      // Wait for the page to load
      await driver.wait(until.elementLocated(By.css('input[type="text"]')), 10000)
      
      // Find the search input using a more reliable selector
      const searchInput = await driver.findElement(By.css('input[type="text"]'))
      await searchInput.click()
      await searchInput.sendKeys("organization")
      
      // Wait for search results to load
      await driver.sleep(2000)
      
      // Find all h4 elements with the specified class
      const titles = await driver.findElements(By.css('h4.font-semibold.text-24pxlh30px.h-\\[60px\\].font-Montserrat.truncate'))
      
      // Get titles from the page
      const pageTitles = []
      for (const title of titles) {
          const text = await title.getText()
          pageTitles.push(text)
      }

      // Get titles from API response
      const apiTitles = response.data.data.map(item => item.name)

      console.log('Items sorted by random (ASC):')
      apiTitles.forEach((title, index) => {
          console.log(`${index + 1}. Title: ${title}`)
      })

      // Verify that we have items in the response
      assert.ok(apiTitles.length > 0, "API response should contain items")
      
    } catch (error) {
      console.error('Test failed:', error)
      throw error
    }
  })
})