// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const axios = require('axios')

describe('SearchWH1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SearchWH1', async function() {
    await driver.get("https://web.stage.vcc.hebronsoft.com/paid-job-openings")
    await driver.manage().window().setRect({ width: 1440, height: 900 })
    await driver.findElement(By.css(".md\\3Amt-5")).click()
    await driver.findElement(By.css(".md\\3Amt-5")).sendKeys("test")
    
    // Wait for search results to load
    await driver.sleep(2000)
    
    // Make API request to get sorted data
    const response = await axios.get('https://api.stage.vcc.hebronsoft.com/web-api/paid-job', {
      params: {
        search: 'test',
        limit: 15,
        offset: 0,
        order: 'DESC',
        orderBy: 'lastRefreshed'
      },
      headers: {
        'Accept': 'application/json, text/plain, */*',
        'Origin': 'https://web.stage.vcc.hebronsoft.com',
        'Referer': 'https://web.stage.vcc.hebronsoft.com/'
      }
    })

    const jobs = response.data.data
    const testItems = []

    // Verify sorting and collect items
    for (let i = 0; i < jobs.length; i++) {
      const currentJob = jobs[i]
      if (currentJob.title.toLowerCase().includes("test")) {
        testItems.push({
          title: currentJob.title,
          lastRefreshed: currentJob.lastRefreshed
        })
      }
      
      // Verify sorting order
      if (i < jobs.length - 1) {
        const currentDate = new Date(currentJob.lastRefreshed)
        const nextDate = new Date(jobs[i + 1].lastRefreshed)
        assert(currentDate >= nextDate, `Sorting order is incorrect: ${currentJob.lastRefreshed} should be after ${jobs[i + 1].lastRefreshed}`)
      }
    }
    
    // Log the results
    console.log(`\nFound ${testItems.length} items containing "test" (sorted by lastRefreshed DESC):`)
    testItems.forEach((item, index) => {
      console.log(`${index + 1}. ${item.title} (Last Refreshed: ${item.lastRefreshed})`)
    })
  })
})